name: Commitlint (prlint)
author: Kevin Taeyoon Jin <hello@kevintyj.com>
description: Ensure PR title match commitlint config
runs:
  using: node20
  main: dist/index.js
inputs:
  download-dependencies:
    description: 'Download commitlint dependencies'
    required: false
    default: 'ignore'
  body:
    description: 'Use body text as commit body using Github style'
    required: false
    default: 'false'
outputs:
  lint-status:
    description: The status of the PR lint
  lint-details:
    description: The output of the PR lint from commitlint
branding:
  icon: git-pull-request
  color: green
