name: Commitlint (prlint)
author: Kevin Taeyoon Jin <hello@kevintyj.com>
description: Ensure PR title match commitlint config
runs:
  using: composite
  steps:
    - run: node $GITHUB_ACTION_PATH/dist/index.js --experimental-default-type=commonjs
      shell: bash
inputs:
  cl-config:
    description: Path to commit lint config (commitlint.config.js)
    default: commitlint.config.js
    required: false
outputs:
  lint-status:
    description: The status of the PR lint
  lint-details:
    description: The output of the PR lint from commitlint
branding:
  icon: git-pull-request
  color: green
