name: 📝 Lint PR title
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🔖Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: 📝Validate PR title with commitlint
        uses: ./
        with:
          download-dependencies: node
          timeout: 60
